package providers

const (
	UKOpenBankingAll = "uk-ob-all"
	UKOAuthAll       = "uk-oauth-all"

	UKMock = "uk-cs-mock"

	UKAlliedIrishBankCorporate    = "uk-ob-aib-gb-corporate"
	UKBankOfScotland              = "uk-ob-bos"
	UKBankOfScotlandBusiness      = "uk-ob-bos-business"
	UKBarclaycard                 = "uk-ob-barclaycard"
	UKBarclays                    = "uk-ob-barclays"
	UKBarclaysBusiness            = "uk-ob-barclays-business"
	UKCapitalOne                  = "uk-ob-capital-one"
	UKChelseaBuildingSociety      = "uk-ob-chelsea-building-society"
	UKDanskeBank                  = "uk-ob-danske"
	UKDanskeBankBusiness          = "uk-ob-danske-business"
	UKFirstDirect                 = "uk-ob-first-direct"
	UKHalifax                     = "uk-ob-halifax"
	UKHSBC                        = "uk-ob-hsbc"
	UKHSBCBusiness                = "uk-ob-hsbc-business"
	UKLloyds                      = "uk-ob-lloyds"
	UKLloydsBusiness              = "uk-ob-lloyds-business"
	UKLloydsCommercial            = "uk-ob-lloyds-corporate"
	UKMSBank                      = "uk-ob-ms"
	UKMBNA                        = "uk-ob-mbna"
	UKMonzo                       = "uk-ob-monzo"
	UKNationwide                  = "uk-ob-nationwide"
	UKNatWest                     = "uk-ob-natwest"
	UKNatWestBusiness             = "uk-ob-natwest-business"
	UKRevolut                     = "uk-ob-revolut"
	UKRoyalBankOfScotland         = "uk-ob-rbs"
	UKRoyalBankOfScotlandBusiness = "uk-ob-rbs-business"
	UKSantander                   = "uk-ob-santander"
	UKTescoBank                   = "uk-ob-tesco"
	UKTide                        = "uk-ob-tide"
	UKTSB                         = "uk-ob-tsb"
	UKUlsterBank                  = "uk-ob-ulster"
	UKUlsterBusiness              = "uk-ob-ulster-business"
	UKVirginMoney                 = "uk-ob-virgin-money"
	UKWise                        = "uk-ob-transferwise"
	UKYorkshireBuildingSociety    = "uk-ob-yorkshire-building-society"

	UKAmericanExpress = "uk-oauth-amex"
	UKStarling        = "uk-oauth-starling"
)
