package providers

const UKOpenBankingAll = "uk-ob-all"
const UKOAuthAll = "uk-oauth-all"

const UKMock = "uk-cs-mock"

const UKAlliedIrishBankCorporate = "uk-ob-aib-gb-corporate"
const UKBankOfScotland = "uk-ob-bos"
const UKBankOfScotlandBusiness = "uk-ob-bos-business"
const UKBarclaycard = "uk-ob-barclaycard"
const UKBarclays = "uk-ob-barclays"
const UKBarclaysBusiness = "uk-ob-barclays-business"
const UKCapitalOne = "uk-ob-capital-one"
const UKChelseaBuildingSociety = "uk-ob-chelsea-building-society"
const UKDanskeBank = "uk-ob-danske"
const UKDanskeBankBusiness = "uk-ob-danske-business"
const UKFirstDirect = "uk-ob-first-direct"
const UKHalifax = "uk-ob-halifax"
const UKHSBC = "uk-ob-hsbc"
const UKHSBCBusiness = "uk-ob-hsbc-business"
const UKLloyds = "uk-ob-lloyds"
const UKLloydsBusiness = "uk-ob-lloyds-business"
const UKLloydsCommercial = "uk-ob-lloyds-corporate"
const UKMSBank = "uk-ob-ms"
const UKMBNA = "uk-ob-mbna"
const UKMonzo = "uk-ob-monzo"
const UKNationwide = "uk-ob-nationwide"
const UKNatWest = "uk-ob-natwest"
const UKNatWestBusiness = "uk-ob-natwest-business"
const UKRevolut = "uk-ob-revolut"
const UKRoyalBankOfScotland = "uk-ob-rbs"
const UKRoyalBankOfScotlandBusiness = "uk-ob-rbs-business"
const UKSantander = "uk-ob-santander"
const UKTescoBank = "uk-ob-tesco"
const UKTide = "uk-ob-tide"
const UKTSB = "uk-ob-tsb"
const UKUlsterBank = "uk-ob-ulster"
const UKUlsterBusiness = "uk-ob-ulster-business"
const UKVirginMoney = "uk-ob-virgin-money"
const UKWise = "uk-ob-transferwise"
const UKYorkshireBuildingSociety = "uk-ob-yorkshire-building-society"

const UKAmericanExpress = "uk-oauth-amex"
const UKStarling = "uk-oauth-starling"
