package providers

type Provider string

const UKOpenBankingAll Provider = "uk-ob-all"
const UKOAuthAll Provider = "uk-oauth-all"

const UKMock Provider = "uk-cs-mock"

const UKAlliedIrishBankCorporate Provider = "uk-ob-aib-gb-corporate"
const UKBankOfScotland Provider = "uk-ob-bos"
const UKBankOfScotlandBusiness Provider = "uk-ob-bos-business"
const UKBarclaycard Provider = "uk-ob-barclaycard"
const UKBarclays Provider = "uk-ob-barclays"
const UKBarclaysBusiness Provider = "uk-ob-barclays-business"
const UKCapitalOne Provider = "uk-ob-capital-one"
const UKChelseaBuildingSociety Provider = "uk-ob-chelsea-building-society"
const UKDanskeBank Provider = "uk-ob-danske"
const UKDanskeBankBusiness Provider = "uk-ob-danske-business"
const UKFirstDirect Provider = "uk-ob-first-direct"
const UKHalifax Provider = "uk-ob-halifax"
const UKHSBC Provider = "uk-ob-hsbc"
const UKHSBCBusiness Provider = "uk-ob-hsbc-business"
const UKLloyds Provider = "uk-ob-lloyds"
const UKLloydsBusiness Provider = "uk-ob-lloyds-business"
const UKLloydsCommercial Provider = "uk-ob-lloyds-corporate"
const UKMSBank Provider = "uk-ob-ms"
const UKMBNA Provider = "uk-ob-mbna"
const UKMonzo Provider = "uk-ob-monzo"
const UKNationwide Provider = "uk-ob-nationwide"
const UKNatWest Provider = "uk-ob-natwest"
const UKNatWestBusiness Provider = "uk-ob-natwest-business"
const UKRevolut Provider = "uk-ob-revolut"
const UKRoyalBankOfScotland Provider = "uk-ob-rbs"
const UKRoyalBankOfScotlandBusiness Provider = "uk-ob-rbs-business"
const UKSantander Provider = "uk-ob-santander"
const UKTescoBank Provider = "uk-ob-tesco"
const UKTide Provider = "uk-ob-tide"
const UKTSB Provider = "uk-ob-tsb"
const UKUlsterBank Provider = "uk-ob-ulster"
const UKUlsterBusiness Provider = "uk-ob-ulster-business"
const UKVirginMoney Provider = "uk-ob-virgin-money"
const UKWise Provider = "uk-ob-transferwise"
const UKYorkshireBuildingSociety Provider = "uk-ob-yorkshire-building-society"

const UKAmericanExpress Provider = "uk-oauth-amex"
const UKStarling Provider = "uk-oauth-starling"
